language: generic

matrix:
  include:
    - os: linux
      env:
        - DOCKERIMAGE=deepmd-kit
        - VARIANT=cpu
        - BASE_IMAGE=ubuntu:focal

    - os: linux
      env:
        - DOCKERIMAGE=deepmd-kit
        - VARIANT=cuda10.1_gpu
        - BASE_IMAGE=nvidia/cuda:10.1-runtime

    - os: linux
      env:
        - DOCKERIMAGE=deepmd-kit
        - VARIANT=cuda10.0_gpu
        - BASE_IMAGE=nvidia/cuda:10.0-runtime

    - os: linux
      env:
        - DOCKERIMAGE=deepmd-kit
        - VARIANT=cuda9.2_gpu
        - BASE_IMAGE=nvidia/cuda:9.2-runtime

env:
  global:
    - VERSION=1.2.0
    - INSTALLER_VERSION=-2

install:
    - docker build --build-arg VARIANT=$VARIANT --build-arg VERSION=$VERSION --build-arg INSTALLER_VERSION=$INSTALLER_VERSION --build-arg BASE_IMAGE=$BASE_IMAGE -t deepmodeling/$DOCKERIMAGE:${VERSION}_${VARIANT} -f $DOCKERIMAGE/Dockerfile .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push deepmodeling/$DOCKERIMAGE:${VERSION}_${VARIANT}
